// Turning a model's answer into something the app will act on. Everything here is
// pure, because this is untrusted input: the model can name a category that doesn't
// exist, repeat one, return a string where cents belong, or quietly get the
// arithmetic wrong. Nothing reaches the database without passing through this.
import { PERIODS, perMonth } from './budget.js'

const CONFIDENCE = ['high', 'medium', 'low']

/**
 * @param raw       proposals as returned by the model
 * @param known     Map of categoryId → { id, name, kind }
 * @param current   Map of categoryId → { period, amount_cents } target in force
 * @returns { proposals, rejected } — rejected is surfaced, not swallowed
 */
export function validateProposals(raw, known, current) {
  const seen = new Set()
  const rejected = []
  const proposals = (Array.isArray(raw) ? raw : []).flatMap(p => {
    const cat = known.get(p?.categoryId)
    if (!cat) { rejected.push(`Ignored a proposal for an unknown category (${String(p?.categoryId).slice(0, 12)})`); return [] }
    if (seen.has(p.categoryId)) { rejected.push(`Ignored a second proposal for ${cat.name}`); return [] }
    // Dollars are what the model is asked for now; cents are still accepted so a
    // plan generated by an earlier release still validates.
    const cents = p.proposedDollars != null
      ? Math.round(Number(p.proposedDollars) * 100)
      : Math.round(Number(p.proposedCents))
    if (!Number.isFinite(cents) || cents < 0) { rejected.push(`Ignored an unusable amount for ${cat.name}`); return [] }
    const period = PERIODS.includes(p.period) ? p.period : 'monthly'
    seen.add(p.categoryId)
    const now = current.get(p.categoryId) ?? null
    return [{
      categoryId: p.categoryId, name: cat.name, kind: cat.kind,
      currentCents: now?.amount_cents ?? null, currentPeriod: now?.period ?? null,
      currentPerMonthCents: now ? perMonth(now.amount_cents, now.period) : null,
      proposedCents: cents, period, proposedPerMonthCents: perMonth(cents, period),
      reason: String(p.reason ?? '').trim().slice(0, 300),
      confidence: CONFIDENCE.includes(p.confidence) ? p.confidence : 'medium',
    }]
  })
  return { proposals, rejected }
}

export const median = values => {
  if (!values.length) return 0
  const s = [...values].sort((a, b) => a - b)
  const mid = Math.floor(s.length / 2)
  return s.length % 2 ? s[mid] : Math.round((s[mid - 1] + s[mid]) / 2)
}

/**
 * The plan's arithmetic, computed here rather than taken from the model — a total
 * that doesn't match its own line items is worse than no total, and it's the first
 * thing a reader checks.
 * @param spendByCategory Map of categoryId → array of monthly amounts (cents)
 */
export function planTotals(proposals, spendByCategory) {
  const expense = proposals.filter(p => p.kind === 'expense')
  // A category with no spending history has no baseline to compare against — and
  // it is often the savings line itself, the destination of the freed money.
  // Counting its target as "extra spending" cancels out the genuine cuts and
  // reports $0 freed next to prose describing hundreds. Keep the two apart.
  const baseline = p => {
    const seen = spendByCategory.get(p.categoryId)
    return seen && seen.length ? median(seen) : null
  }
  const comparable = expense.filter(p => baseline(p) != null)
  const newly = expense.filter(p => baseline(p) == null)

  const typical = comparable.reduce((n, p) => n + baseline(p), 0)
  const proposedComparable = comparable.reduce((n, p) => n + p.proposedPerMonthCents, 0)

  return {
    // Every target the plan sets, for reference
    proposed_per_month_cents: expense.reduce((n, p) => n + p.proposedPerMonthCents, 0),
    current_per_month_cents: expense.reduce((n, p) => n + (p.currentPerMonthCents ?? 0), 0),
    typical_per_month_cents: typical,
    // What the plan actually releases: the sum of real reductions
    frees_per_month_cents: comparable.reduce((n, p) => n + Math.max(0, baseline(p) - p.proposedPerMonthCents), 0),
    // Net movement on categories we can compare, so a raise still shows up
    change_per_month_cents: proposedComparable - typical,
    // Newly budgeted categories are reported, not silently netted off
    newly_budgeted_per_month_cents: newly.reduce((n, p) => n + p.proposedPerMonthCents, 0),
    newly_budgeted: newly.map(p => p.name),
    cuts: comparable.filter(p => p.proposedPerMonthCents < baseline(p)).length,
    raises: comparable.filter(p => p.proposedPerMonthCents > baseline(p)).length,
  }
}

// A plan that cuts a category below what it is contractually committed to is not a
// plan, it's a wish. Recurring bills give us that floor.
export function commitmentConflicts(proposals, commitments) {
  const perMonthCommitted = new Map()
  const PER_MONTH = { weekly: 52 / 12, fortnightly: 26 / 12, monthly: 1, quarterly: 1 / 3, yearly: 1 / 12 }
  for (const c of commitments) {
    if (!c.categoryId) continue
    const monthly = Math.round(c.cents * (PER_MONTH[c.frequency] ?? 1))
    perMonthCommitted.set(c.categoryId, (perMonthCommitted.get(c.categoryId) || 0) + monthly)
  }
  return proposals.flatMap(p => {
    const committed = perMonthCommitted.get(p.categoryId)
    if (!committed || p.proposedPerMonthCents >= committed) return []
    return [{ categoryId: p.categoryId, name: p.name, committedPerMonthCents: committed, proposedPerMonthCents: p.proposedPerMonthCents }]
  })
}

// A stored plan row → the shape the UI renders. Plans written by earlier builds
// (or a run that stored a partial summary) are missing keys the page reads
// unguarded, and a missing `totals` is a blank screen rather than a bad number.
// Normalising in one place means every route returns the same complete object.
export function planResponse(row) {
  if (!row) return null
  // summary lived in a TEXT column for one release, so it can arrive as a JSON
  // string. Parsing here means a plan written by any build reads correctly, and a
  // genuinely plain summary is kept as prose rather than leaking as a payload.
  let blob = row.summary
  if (typeof blob === 'string') {
    try { blob = JSON.parse(blob) } catch { blob = { summary: blob } }
  }
  if (!blob || typeof blob !== 'object' || Array.isArray(blob)) blob = {}
  return {
    ...row,
    // Never fall back to the raw row value — that is what leaked the payload
    summary: typeof blob.summary === 'string' ? blob.summary : '',
    goalOutlook: Array.isArray(blob.goalOutlook) ? blob.goalOutlook : [],
    warnings: Array.isArray(blob.warnings) ? blob.warnings : [],
    rejected: Array.isArray(blob.rejected) ? blob.rejected : [],
    conflicts: Array.isArray(blob.conflicts) ? blob.conflicts : [],
    effort: blob.effort ?? null,
    proposals: Array.isArray(row.proposals) ? row.proposals : [],
    untouched: (blob.untouched && typeof blob.untouched === 'object') ? blob.untouched : { count: 0, names: [] },
    window: blob.window ?? null,
    goalCount: blob.goalCount ?? 0,
    totals: {
      proposed_per_month_cents: 0,
      current_per_month_cents: 0,
      typical_per_month_cents: 0,
      change_per_month_cents: 0,
      goals_need_per_month_cents: 0,
      frees_per_month_cents: 0,
      newly_budgeted_per_month_cents: 0,
      cuts: 0,
      raises: 0,
      ...(blob.totals && typeof blob.totals === 'object' ? blob.totals : {}),
    },
  }
}
